version: '3.8'
services:
  web:
    build: .
    command: sh -c " python manage.py migrate && \
                     python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miletus_user:miletus_password@db:5432/miletus_db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=miletus_db
      - POSTGRES_USER=webna
      - POSTGRES_PASSWORD=webna@2024

volumes:
  postgres_data:
